POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvbm55IiwiaWQiOiI2M2ZmZGRiYmQ3Njc1OGE3NTQ4ZTBmMTkiLCJpYXQiOjE2Nzc4NDQ4NzR9.ynANzbKe1HzFbHz24Q9EVwxNTRvw07tlwcwr-kkmwUo

{
    "title": "Pies are still really nice",
    "author": "Ronny",
    "url": "t324",
    "likes": 77
    
}